//! Single seat: Unix name `home`, HOME=/home. Root is privilege, not login.

use std::collections::BTreeMap;
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::Path;
use std::process::Command;

use crate::error::Result;
use crate::kinds::Host;

pub const NAME: &str = "home";
pub const UID: u32 = 1000;
pub const GID: u32 = 1000;
pub const HOME: &str = "/home";
pub const GROUP_SEAT: u32 = 71;
pub const GROUP_VIDEO: u32 = 44;
pub const GROUP_INPUT: u32 = 14;
pub const HELPERS: &str = "/lib/oath";

pub fn is_seat_svc(id: &str) -> bool {
    let name = id.strip_prefix("svc:").unwrap_or(id);
    matches!(
        name,
        "river" | "sola-bus" | "sola-call" | "sola-river" | "sola-shell" | "sola-session"
    )
}

pub fn passwd_file() -> String {
    format!("root:x:0:0:root:/root:/bin/sh\n{NAME}:x:{UID}:{GID}:{NAME}:{HOME}:/bin/sh\n")
}

pub fn group_file() -> String {
    format!(
        "root:x:0:\n\
         {NAME}:x:{GID}:\n\
         seat:x:{GROUP_SEAT}:{NAME}\n\
         video:x:{GROUP_VIDEO}:{NAME}\n\
         input:x:{GROUP_INPUT}:{NAME}\n\
         wheel:x:10:{NAME}\n"
    )
}

pub fn shadow_file() -> String {
    format!("root:*:1:0:99999:7:::\n{NAME}:*:1:0:99999:7:::\n")
}

pub fn write_side_effects(desired: &Host) -> Result<()> {
    let _ = fs::create_dir_all("/etc");
    fs::write("/etc/hostname", format!("{}\n", desired.hostname))?;
    fs::write(
        "/etc/hosts",
        format!("127.0.0.1 localhost\n::1 localhost\n127.0.1.1 {}\n", desired.hostname),
    )?;
    write_profile(&desired.env)?;
    Ok(())
}

pub fn write_profile(env: &BTreeMap<String, String>) -> Result<()> {
    let body = profile_body(env);
    fs::write("/etc/profile", &body)?;
    if Path::new(HOME).is_dir() {
        let p = format!("{HOME}/.profile");
        fs::write(&p, &body)?;
        let _ = Command::new("/bin/chown").args(["-R", &format!("{UID}:{GID}"), &p]).status();
    }
    Ok(())
}

pub fn profile_body(env: &BTreeMap<String, String>) -> String {
    let mut body = String::from("# generated by oath from host:local env\n");
    for (k, v) in env {
        if !valid_env_name(k) || v.contains('\n') || v.contains('\0') {
            continue;
        }
        body.push_str("export ");
        body.push_str(k);
        body.push('=');
        body.push_str(&sh_single_quote(v));
        body.push('\n');
    }
    body
}

pub fn valid_env_name(name: &str) -> bool {
    let mut cs = name.chars();
    match cs.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' => {}
        _ => return false,
    }
    cs.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn sh_single_quote(v: &str) -> String {
    format!("'{}'", v.replace('\'', "'\\''"))
}

/// DRM + evdev nodes the seat compositor must open (no udevd).
pub fn open_device_nodes() {
    chmod_tree("/dev/dri", 0o660, 0, GROUP_VIDEO);
    chmod_tree("/dev/input", 0o660, 0, GROUP_INPUT);
}

fn chmod_tree(dir: &str, mode: u32, uid: u32, gid: u32) {
    let Ok(rd) = fs::read_dir(dir) else { return };
    for e in rd.flatten() {
        let p = e.path();
        let _ = fs::set_permissions(&p, fs::Permissions::from_mode(mode));
        let path = p.to_string_lossy().into_owned();
        let _ = Command::new("/bin/chown").args([&format!("{uid}:{gid}"), &path]).status();
    }
}
