//! Single seat: Unix name `home`, HOME=/home. Root is privilege, not login.

use std::collections::BTreeMap;
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::process::Command;

use crate::error::Result;
use crate::kinds::Host;

pub const NAME: &str = "home";
pub const UID: u32 = 1;
pub const GID: u32 = 1;
pub const HOME: &str = "/home";
pub const HELPERS: &str = "/lib/oath";

pub fn is_seat_svc(id: &str) -> bool {
    let name = id.strip_prefix("svc:").unwrap_or(id);
    matches!(
        name,
        "river" | "sola-bus" | "sola-call" | "sola-river" | "sola-shell" | "sola-session"
    )
}

pub fn passwd_file() -> String {
    format!("root:x:0:0:root:/root:/bin/sh\n{NAME}:x:{UID}:{GID}:{NAME}:{HOME}:/bin/sh\n")
}

pub fn group_file() -> String {
    format!("root:x:0:\n{NAME}:x:{GID}:\n")
}

pub fn shadow_file() -> String {
    format!("root:*:1:0:99999:7:::\n{NAME}:*:1:0:99999:7:::\n")
}

pub fn write_side_effects(desired: &Host) -> Result<()> {
    let _ = fs::create_dir_all("/etc");
    fs::write("/etc/hostname", format!("{}\n", desired.hostname))?;
    fs::write(
        "/etc/hosts",
        format!("127.0.0.1 localhost\n::1 localhost\n127.0.1.1 {}\n", desired.hostname),
    )?;
    write_profile(&desired.env)?;
    Ok(())
}

pub fn write_profile(env: &BTreeMap<String, String>) -> Result<()> {
    let body = profile_body(env);
    fs::write("/etc/profile", &body)?;
    let _ = fs::set_permissions("/etc/profile", fs::Permissions::from_mode(0o644));
    let _ = Command::new("/bin/chown").args(["0:0", "/etc/profile"]).status();
    Ok(())
}

pub fn profile_body(env: &BTreeMap<String, String>) -> String {
    let mut body = String::from(
        "# generated by oath from host:local env (root-owned; do not copy to $HOME)\n",
    );
    for (k, v) in env {
        if !valid_env_name(k) || v.contains('\n') || v.contains('\0') {
            continue;
        }
        body.push_str("export ");
        body.push_str(k);
        body.push('=');
        body.push_str(&sh_single_quote(v));
        body.push('\n');
    }
    body
}

pub fn valid_env_name(name: &str) -> bool {
    let mut cs = name.chars();
    match cs.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' => {}
        _ => return false,
    }
    cs.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn sh_single_quote(v: &str) -> String {
    format!("'{}'", v.replace('\'', "'\\''"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn home_is_uid_1() {
        assert_eq!(UID, 1);
        assert_eq!(GID, 1);
        assert!(passwd_file().contains("home:x:1:1:home:/home:"));
        let g = group_file();
        assert!(g.contains("home:x:1:"));
        assert!(!g.contains("wheel"));
        assert!(!g.contains("video"));
        assert!(!g.contains("seat:"));
    }

    #[test]
    fn profile_is_root_owned_copy() {
        let mut env = BTreeMap::new();
        env.insert("GROK_DISABLE_AUTOUPDATER".into(), "1".into());
        let b = profile_body(&env);
        assert!(b.contains("host:local env"));
        assert!(b.contains("GROK_DISABLE_AUTOUPDATER='1'"));
        assert!(!b.contains("/home"));
    }
}

/// DRM + evdev nodes the seat compositor must open (no udevd).
pub fn open_device_nodes() {
    chmod_tree("/dev/dri", 0o660, 0, GID);
    chmod_tree("/dev/input", 0o660, 0, GID);
}

fn chmod_tree(dir: &str, mode: u32, uid: u32, gid: u32) {
    let Ok(rd) = fs::read_dir(dir) else { return };
    for e in rd.flatten() {
        let p = e.path();
        let _ = fs::set_permissions(&p, fs::Permissions::from_mode(mode));
        let path = p.to_string_lossy().into_owned();
        let _ = Command::new("/bin/chown").args([&format!("{uid}:{gid}"), &path]).status();
    }
}
